window.ajaxResult = {
	"status":"success",
	"msg":"",
	"data":{
		"dataList":[{
			"id":1,
			"userImg":"../../images/user-icon.png",
			"notesCount":3,
			"source":"ebay",
			"creatorName":"张小三",
			"lastModified":"2015-3-14",
			"content":"这个SKU缺货，20号前会补齐"
		},{
			"id":2,
			"userImg":"../../images/user-icon.png",
			"notesCount":5,
			"source":"新品开发",
			"creatorName":"李小四",
			"lastModified":"2015-3-14",
			"content":"这个改发红色"
		},{
			"id":3,
			"userImg":"../../images/user-icon.png",
			"notesCount":5,
			"source":"新品开发",
			"creatorName":"李小四",
			"lastModified":"2015-3-14",
			"content":"这个改发红色"
		},{
			"id":4,
			"userImg":"../../images/user-icon.png",
			"notesCount":5,
			"source":"新品开发",
			"creatorName":"李小四",
			"lastModified":"2015-3-14",
			"content":"明天发"
		},{
			"id":5,
			"userImg":"../../images/user-icon.png",
			"notesCount":5,
			"source":"新品开发",
			"creatorName":"李小四",
			"lastModified":"2015-3-14",
			"content":"这个换货的"
		},{
			"id":6,
			"userImg":"../..//images/user-icon.png",
			"notesCount":5,
			"source":"新品开发",
			"creatorName":"李小四",
			"lastModified":"2015-3-14",
			"content":"这个不发"
		}]
	}

}